---
- name: replace sshd_config
  become: true
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
- name: restart ssh server
  become: true
  service:
    name: sshd
    state: restarted
