---
- name: add authorized keys
  become: true
  authorized_key:
    user: root
    key: "{{ lookup('file', 'files/id_ed25519.pub') }}"
- name: replace sshd_config
  become: true
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
- name: restart ssh server
  become: true
  service:
    name: sshd
    state: restarted
