---
- name: check user
  hosts: all
  tasks:
    - name: is root
      debug:
        msg: "Is root"
      when:
        - ansible_user == "root"
    - name: is not root
      debug:
        msg: "Is not root"
      when:
        - ansible_user != "root"
    - name: hostname
      debug:
        msg: "Hostname: {{ hostvars['remote1']['ansible_host'] }}"
